### ISSUE TITLE
Tkinter error

### ISSUE THREAD

**Issue by Linkdash2019** [vbe0201/3DS.py#22]
I can see that tkinter is installed to this python client but when run I get the error below (program worked fine on widows pc)
![WIN_20230702_18_44_25_Pro](https://github.com/vbe0201/3DS.py/assets/110307943/cc47519b-f5e8-40b8-a445-c6377baf13a1)
this is my code:

import time
from tkinter import *
from tkinter import ttk

if __name__ == '__main__':
    print('3DS.py brings Python to your Nintendo 3DS!')

print('starting up program in 3')
time.sleep(1)
print('2')
time.sleep(1)
print('1')
time.sleep(1)

root = Tk()
frm = ttk.Frame(root, padding=10)
frm.grid()
ttk.Label(frm, text="Hello World!").grid(column=0, row=0)
ttk.Button(frm, text="Quit", command=root.destroy).grid(column=1, row=0)
root.mainloop()

**Comment by ENDERZOMBI102** [comment]
you cannot use tkinter with 3ds.py

**Comment by Linkdash2019** [comment]
Dang :/ thanks for letting me know!

**Comment by ExtraBytez** [comment]
imagine if you could though that would be cursed XD
