### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by vbe0201** [vbe0201/3DS.py#3]
3DS.py should have a new icon which really combines "3DS" and "Python" instead of just having the Python logo. I'm thinking about something like a 3DS console in Python colors.

_This is primarily addressed to myself so I won't forget about it. I would however be glad to review submissions. Just hit me up on Discord (Vale#5252)._

**Comment by richardbmx** [comment]
@vbe0201 Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your projec

**Comment by vbe0201** [comment]
Ahoy there, Richard! Thanks for your offer, that would be awesome! As stated above, some logo that combines the Nintendo 3DS console and the colors of Python (see `logo.png` in the project root) is what I was thinking of. A 500x500 PNG would be sufficient. I'm looking forward to your PR!

Kind regards.

**Comment by richardbmx** [comment]
@vbe0201  Perfect I will work on it

**Comment by richardbmx** [comment]
@vbe0201 Hello, I would like to present this logo design for your project, it is inspired by the fusion of 3DS with Python as you can see it adapts very well in different colors is a simple and flexible design, I hope you like it if you want some change you should only request it and I do it with pleasure.

![logo135](https://user-images.githubusercontent.com/35604837/58989858-b4472280-87b2-11e9-9b05-c9bd46b6bc73.png)

**Comment by vbe0201** [comment]
Hello Richard, many thanks for your effort, these are super cool! I'm struggling to decide between the first one and the last one because they're both great. I'd suggest to add a similar gray background color to the first one in the picture if that's ok. Then I'd love to merge a PR that replaces the old logo and, of course, credits you in the README for the awesome work. :)

**Comment by richardbmx** [comment]
@vbe0201  you mean to put a gray background like that?

![logo13522](https://user-images.githubusercontent.com/35604837/59061047-7dcfdd00-8870-11e9-94fa-e6ce80dd9997.png)

This would saturate the design a lot and it will look very overloaded I would not recommend it

**Comment by vbe0201** [comment]
I honestly don't even think this looks that bad. But I'll leave that to you. I'd take whatever you consider as best-looking.

**Comment by richardbmx** [comment]
@vbe0201  I present here a folder of google drive with all the necessary files to use the logo within the folder you will find different variations of the logo so that you can use it in any way, additional to this there is a file that makes delivery of the copyright for that you can use the logo without problems.

[Google Drive](https://drive.google.com/open?id=1NT72A82jsIO9CXL4B7w8S39S4Zoc1DwG)

**Comment by vbe0201** [comment]
Thanks for your contribution, Richard, I really like all these awesome assets. I'll make sure to add them as well as giving credit to you in the README when I've got time.

**Comment by vbe0201** [comment]
A new app icon with your design has been added to the repository and you've been properly credited, this issue can therefore be closed. Thanks again!
